### ISSUE TITLE
Not able to invoke the rag_chain given in the example Notebook

### ISSUE THREAD

**Issue by testerops01** [Renumics/renumics-rag#16]
I am trying to implement the `renumics-spotlight` package and I was referring to the example notebook that is given and followed the tutorial mentioned in this [link](https://itnext.io/visualize-your-rag-data-eda-for-retrieval-augmented-generation-0701ee98768f).

I had to make some changes in the code in my local notebook - and the steps upto when the `rag_chain` is invoked works fine, but  these steps fail due to Authentication error from OpenAI , which I am not able to understand why?

```
question = "Who built the nuerburgring"
response = rag_chain.invoke(question)
answer = response["answer"]
answer
```
Since the error stack trace is large, I'm sharing this via a [link](https://justpaste.it/3omdx)

Do we need to provide any additional authentication here since I've already set the env variable and also tried doing this before invoking the `rag_chain`

```
from getpass import getpass
OPENAI_API_KEY = getpass()
import os

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
```

But this still makes no difference. Can you please help me out in this issue.

**Comment by druzsan** [comment]
Hi @testerops01,
I can imagine a couple of reasons for this:
- Your API key is indeed incorrect.
- Your API key is correct but you aren't using the intended way to set environment variables in Python Notebooks (`%set OPENAI_API_KEY=<Paste your API key here>`).

To check the first assumption, run the minimal getting started example by [OpenAI](https://platform.openai.com/docs/quickstart/step-3-sending-your-first-api-request):
```python
from openai import OpenAI
client = OpenAI(api_key="<Paste your API key here>")

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
    {"role": "user", "content": "Compose a poem that explains the concept of recursion in programming."}
  ]
)

print(completion.choices[0].message)
```

If it works, try to set the `OPENAI_API_KEY` environment variable and run the code above without setting `api_key="..."`.

**Comment by testerops01** [comment]
I think I know what the mistake was. 
I was setting 

`%env OPENAI_API_KEY="sk-proj-****"`

The key was inside the brackets. If I remove the brackets I don't see the error. I've set like this now

`%env OPENAI_API_KEY=sk-proj-****`

**Comment by testerops01** [comment]
One more thing -

```
from langchain_core.documents import Document

# add new splits to the vector store
from langchain_core.documents import Document

if new_splits_ids:
    docs_vectorstore.add_documents(
        documents=[split["doc"] for split in new_splits_ids],
        ids=[split["id"] for split in new_splits_ids],
    )
docs_vectorstore.persist()
```

Gives me 

<img width="1148" alt="Screenshot 2024-05-23 at 7 46 41 PM" src="https://github.com/Renumics/renumics-rag/assets/170226716/8ac2e2c1-4b78-4042-acb1-f61dca63468b">


When I try to fix this using

```
import hashlib
import json
from langchain_core.documents import Document
from chromadb.errors import DuplicateIDError


def stable_hash(doc: Document) -> str:
    """Stable hash document based on its metadata."""
    return hashlib.sha1(json.dumps(doc.metadata, sort_keys=True).encode()).hexdigest()


split_ids = list(map(stable_hash, splits))

try:
    docs_vectorstore.add_documents(splits, ids=split_ids)
except DuplicateIDError:
    print("Duplicate IDs found. Ignoring and proceeding.")

docs_vectorstore.persist() 
```

It outputs

> 
> Duplicate IDs found. Ignoring and proceeding.
> [/opt/anaconda3/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:119](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:119): LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
>   warn_deprecated(

This adversely affects my rag chain and once invoked, it shows

`"I'm sorry, but I can't provide the answer because the document extract provided does not contain any information about what F1 means. \n\nSOURCES: N/A"`

Why does this happen? I've changed the `docs` folder name as well the Chroma collection name and persist directory to see if the earlier data doesn't clash with anything?

**Comment by Renumics** [comment]
Hi @testerops01, we discussed a similar problem in #11.
You have two options:
- if you are sure that you won't add the same document/chunk twice by mistake, then just drop `split_ids` completely. In this case, IDs will be generated randomized automatically, but if you add the same document/chunk to the vectorstore, it will be quietly added without warnings or errors, what can affect the RAG;
- if you want to ensure uniqueness of the documents/chunks in the vectorstore, be sure to have unique metadata for each document, e.g. doc name+doc page+split start character. In the article linked above, we achieve this by using `RecursiveCharacterTextSplitter(..., add_start_index=True)`. Without this flag, it would also fail. To give you more help on this, I need to see you document loading and splitting code.

**Comment by testerops01** [comment]
[F1_RAG.md](https://github.com/user-attachments/files/15786809/F1_RAG.md)
@Renumics  I've attached the failing code from start. The OPEN_API_KEY that is present in the code is now deleted.

**Comment by druzsan** [comment]
@testerops01 I'm not sure if it is a bug or an allowed behavior, but starting from some point, `RecursiveCharacterTextSplitter` generates overlapping chunks starting from the same point. So the exception is indeed correct in this way.

One way to fix this is to index only the longest of the overlapping chunks. In your code, you have to insert the following snippet **between** chunk generation and vectorstore creation:
```python
indices_to_remove = set()
for i, split_id in enumerate(splits_ids):
    for j in range(i + 1, len(splits_ids)):
        if splits_ids[j]["id"] == split_id["id"]:
            if len(splits[j].page_content) > len(splits[i].page_content):
                indices_to_remove.add(i)
            else:
                indices_to_remove.add(j)
for index in sorted(indices_to_remove, reverse=True):
    del splits[index]
    del splits_ids[index]
```

**Comment by testerops01** [comment]
@druzsan Thanks so much. The above resolution works. I am happy to close this.
