### ISSUE TITLE
ChromaDB does not update documents after adding custom documents

### ISSUE THREAD

**Issue by fabiomonticelli23** [Renumics/renumics-rag#22]
I have added a custom function which when i load a new pdf or txt it load in chromaDB instance using the "create-db --exist-ok --on-match ignore" to index it.
The index is successfully, but i can only access the document information after restarting the app.

there is a way to do this while the app is ruinning?

FIrst run output:
![image](https://github.com/user-attachments/assets/882d7d93-2fe5-48e8-aad7-ac6fb6045c4f)

Second run output:
![image](https://github.com/user-attachments/assets/cffdcf2f-8ed7-417c-be14-548b7cff3eab)

**Comment by markus-stoll** [comment]
hey @fabiomonticelli23, no it needs to be restarted. The data is loaded from chromaDB and exported to a pandas dataframe for visualization in spotlight
